Ordinary:
Workcenter:         M1
  RGB:                85;100;31
  Release:            0
  Status:             A

Workcenter:         M2
  RGB:                4;50;230
  Release:            0
  Status:             A

Workcenter:         M3
  RGB:                174;48;162
  Release:            0
  Status:             A

Workcenter:         M4
  RGB:                51;145;139
  Release:            0
  Status:             A

