Ordinary:
Workcenter:         Trimming (M1)
  RGB:                82;113;90
  Release:            0
  Status:             A

Workcenter:         Drilling (M2)
  RGB:                84;20;170
  Release:            0
  Status:             A

Workcenter:         Polishing (M3)
  RGB:                9;141;205
  Release:            0
  Status:             A

Workcenter:         Testing (M4)
  RGB:                15;213;54
  Release:            0
  Status:             A

